# Generated by Django 3.2.4 on 2021-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='costumers/'),
        ),
    ]
