# Generated by Django 3.2.4 on 2021-07-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_costumer_photo'),
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte', models.BigIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('date_exp', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.costumer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='creditcard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.creditcard'),
            preserve_default=False,
        ),
    ]
