# Generated by Django 3.2.4 on 2021-07-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210703_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='creditcard',
        ),
    ]
