# Generated by Django 3.2.4 on 2021-07-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_order_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='CVV',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
